DROP TABLE IF EXISTS users;
CREATE TABLE users (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name text NOT NULL, 
    last_name text NOT NULL, 
    email VARCHAR(200) NOT NULL, 
    user_password VARCHAR(200) NOT NULL, 
    student boolean NOT NULL, 
    tutor boolean NOT NULL,
    gender VARCHAR NOT NULL,
    rating INTEGER DEFAULT NULL,
    fee INTEGER,
    CONSTRAINT if_tutor_then_fee_is_not_null 
    CHECK ( (NOT tutor) OR (fee IS NOT NULL) ),
    CONSTRAINT tutor_or_student_must_be_true 
    CHECK ( (tutor) OR (student) ),
    UNIQUE (email)
)